// agentkit capabilities and extension points, grouped by area.
export const plugins = [
  { name: "OpenAI", category: "provider" },
  { name: "Kimi", category: "provider" },
  { name: "Gemini", category: "provider" },
  { name: "Mock Provider", category: "provider" },
  { name: "Tool Registry", category: "tools" },
  { name: "Toolgen", category: "tools" },
  { name: "Neutral Payloads", category: "tools" },
  { name: "Tool Retriever", category: "tools" },
  { name: "RAG Embedder", category: "retrieval" },
  { name: "Embedding Cache", category: "retrieval" },
  { name: "History Store", category: "retrieval" },
  { name: "Text", category: "modality" },
  { name: "Voice", category: "modality" },
  { name: "STT / TTS", category: "modality" },
  { name: "Agent Loop", category: "runtime" },
  { name: "Tool Planner", category: "runtime" },
  { name: "Cancellation", category: "runtime" },
  { name: "Replay", category: "events" },
  { name: "Projection", category: "events" },
  { name: "In-Memory Bus", category: "events" },
  { name: "Redis Bus", category: "events" },
  { name: "MCP", category: "tools" },
];
