// kaji capabilities and extension points, grouped by area.
export const plugins = [
  { name: "OpenAI", category: "provider" },
  { name: "Anthropic", category: "provider" },
  { name: "GitHub (experimental)", category: "tools" },
  { name: "Echo", category: "tools" },
  { name: "Neutral Payloads", category: "tools" },
  { name: "Risk Policy", category: "tools" },
  { name: "Approvals", category: "tools" },
  { name: "Idempotency", category: "tools" },
  { name: "Context Windows", category: "runtime" },
  { name: "Text", category: "modality" },
  { name: "Voice (experimental)", category: "modality" },
  { name: "Agent Loop", category: "runtime" },
  { name: "Tool Planner", category: "runtime" },
  { name: "Cancellation", category: "runtime" },
  { name: "Replay", category: "events" },
  { name: "Projection", category: "events" },
  { name: "In-Memory Journal", category: "events" },
  { name: "Bounded Subscribers", category: "events" },
];
