"use client";
import { RiCheckLine, RiFileCopyLine } from "@remixicon/react";
import type {
  ButtonHTMLAttributes,
  CSSProperties,
  ComponentProps,
  HTMLAttributes,
  ReactElement,
  ReactNode,
  Ref,
  RefObject,
} from "react";
import { createContext, use, useCallback, useRef } from "react";
import { buttonVariants } from "@components/ui/button";
import { cn } from "@lib/utils";
import { ScrollArea, ScrollBar, ScrollViewport } from "./scroll-area";
import { useCopyButton } from "@hooks/use-copy-button";

export interface CodeBlockProps extends ComponentProps<"figure"> {
  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: ReactNode;

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean;

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean;

  viewportProps?: HTMLAttributes<HTMLElement>;

  /**
   * show line numbers
   */
  "data-line-numbers"?: boolean;

  /**
   * @defaultValue 1
   */
  "data-line-numbers-start"?: number;

  Actions?: (props: { className?: string; children?: ReactNode }) => ReactNode;
}

const TabsContext = createContext<{
  containerRef: RefObject<HTMLDivElement | null>;
  nested: boolean;
} | null>(null);

export function Pre(props: ComponentProps<"pre">) {
  return (
    <pre {...props} className={cn("min-w-full w-max *:flex *:flex-col", props.className)}>
      {props.children}
    </pre>
  );
}

const EMPTY_VIEWPORT_PROPS = {};

export function CodeBlock({
  ref,
  title,
  allowCopy,
  keepBackground = false,
  icon,
  viewportProps = EMPTY_VIEWPORT_PROPS,
  children,
  Actions = (props) => <div {...props} className={cn("empty:hidden", props.className)} />,
  ...props
}: CodeBlockProps) {
  const isTab = use(TabsContext) !== null;
  const areaRef = useRef<HTMLDivElement>(null);
  allowCopy ??= !isTab;
  const bg = cn(
    "bg-fd-secondary",
    keepBackground && "bg-(--shiki-light-bg) dark:bg-(--shiki-dark-bg)",
  );
  const onCopy = useCallback(() => {
    const pre = areaRef.current?.getElementsByTagName("pre").item(0);
    if (!pre) return;
    const clone = pre.cloneNode(true) as HTMLElement;
    clone.querySelectorAll(".nd-copy-ignore").forEach((node) => {
      node.remove();
    });
    void navigator.clipboard.writeText(clone.textContent ?? "");
  }, []);
  return (
    <figure
      ref={ref}
      dir="ltr"
      {...props}
      className={cn(
        isTab ? [bg, "rounded-lg"] : "my-4 rounded-lg bg-fd-card",
        "group shiki relative border shadow-sm outline-none not-prose overflow-hidden text-sm",
        props.className,
      )}
    >
      {title ? (
        <div
          className={cn(
            "group flex text-fd-muted-foreground items-center gap-2 ps-3 h-9.5 pr-1 bg-fd-muted",
            isTab && "border-b",
          )}
        >
          {typeof icon === "string" ? (
            <div
              className="[&_svg]:size-3.5"
              // react-doctor-disable-next-line no-danger, react-doctor/no-danger
              dangerouslySetInnerHTML={{
                __html: icon,
              }}
            />
          ) : (
            icon
          )}
          <figcaption className="flex-1 truncate">{title}</figcaption>
          {Actions({
            children: allowCopy && <CopyButton onCopy={onCopy} />,
          })}
        </div>
      ) : (
        Actions({
          className: "absolute top-1 right-1 z-2 text-fd-muted-foreground",
          children: allowCopy && <CopyButton onCopy={onCopy} />,
        })
      )}
      <div
        ref={areaRef}
        {...viewportProps}
        className={cn(
          !isTab && [bg, "rounded-none border border-x-0 border-b-0"],
          "text-[13px] overflow-auto max-h-[600px] bg-fd-muted/50 fd-scroll-container",
          viewportProps.className,
          !title && "border-t-0",
        )}
        style={
          {
            // space for toolbar
            "--padding-right": !title ? "calc(var(--spacing) * 8)" : undefined,
            counterSet: props["data-line-numbers"]
              ? `line ${Number(props["data-line-numbers-start"] ?? 1) - 1}`
              : undefined,
            ...viewportProps.style,
          } as CSSProperties
        }
      >
        {children}
      </div>
    </figure>
  );
}
function CopyButton({
  className,
  onCopy,
  ...props
}: ButtonHTMLAttributes<HTMLButtonElement> & {
  onCopy: () => void;
}): ReactElement {
  const [checked, onClick] = useCopyButton(onCopy);

  return (
    <button
      type="button"
      className={cn(
        buttonVariants({
          variant: "ghost",
          size: "icon",
        }),
        "transition-opacity size-7 border-none  group-hover:opacity-100",
        "opacity-0 group-hover:opacity-100",
        "group-hover:opacity-100",
        className,
      )}
      aria-label="Copy Text"
      onClick={onClick}
      {...props}
    >
      <RiCheckLine size={14} className={cn("transition-transform", !checked && "scale-0")} />
      <RiFileCopyLine
        size={14}
        className={cn("absolute transition-transform", checked && "scale-0")}
      />
    </button>
  );
}
function _CodeBlockOld({
  ref,
  title,
  allowCopy = true,
  keepBackground = false,
  icon,
  viewportProps,
  ...props
}: CodeBlockProps & { ref?: Ref<HTMLElement> }) {
  const areaRef = useRef<HTMLDivElement>(null);
  const onCopy = useCallback(() => {
    const pre = areaRef.current?.getElementsByTagName("pre").item(0);

    if (!pre) return;

    const clone = pre.cloneNode(true) as HTMLElement;
    clone.querySelectorAll(".nd-copy-ignore").forEach((node) => {
      node.remove();
    });

    void navigator.clipboard.writeText(clone.textContent ?? "");
  }, []);

  return (
    <figure
      ref={ref}
      {...props}
      className={cn(
        "not-prose group fd-codeblock relative my-6 overflow-hidden rounded-lg border bg-fd-secondary/50 text-sm",
        keepBackground && "bg-[var(--shiki-light-bg)] dark:bg-[var(--shiki-dark-bg)]",
        props.className,
      )}
    >
      {title ? (
        <div className="flex flex-row items-center gap-2 border-b bg-fd-muted px-4 py-1.5">
          {icon ? (
            <div
              className="text-fd-muted-foreground [&_svg]:size-3.5"
              // react-doctor-disable-next-line no-danger, react-doctor/no-danger
              dangerouslySetInnerHTML={
                typeof icon === "string"
                  ? {
                      __html: icon,
                    }
                  : undefined
              }
            >
              {typeof icon !== "string" ? icon : null}
            </div>
          ) : null}
          <figcaption className="flex-1 truncate text-fd-muted-foreground">{title}</figcaption>
          {allowCopy ? <CopyButton className="-me-2" onCopy={onCopy} /> : null}
        </div>
      ) : (
        allowCopy && (
          <CopyButton className="absolute right-2 top-2 z-[2] backdrop-blur-md" onCopy={onCopy} />
        )
      )}
      <ScrollArea ref={areaRef} dir="ltr">
        <ScrollViewport
          {...viewportProps}
          className={cn("max-h-[600px]", viewportProps?.className)}
        >
          {props.children}
        </ScrollViewport>
        <ScrollBar orientation="horizontal" />
      </ScrollArea>
    </figure>
  );
}
